name: gh-pages-index
on:
  push:
    branches:
      - main  
jobs:
  gh-pages-index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: |
        # gh-pages
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git branch -d gh-pages &> /dev/null || echo "gh-pages branch not found. ignored."
        echo "create branch"
        git checkout -b gh-pages
        rm -rf .github/
        echo "create index file"
        touch index.md
        echo "{% include_relative $FILE1 %}" >> index.md
        echo "{% include_relative $FILE2 %}" >> index.md
        echo "create Jekyll config"
        touch _config.yml
        echo "push to remote"
        git add .
        git commit -m "added index"
        git push -f origin gh-pages
      env:
        FILE1: README.md
        FILE2: file.md
